### ISSUE TITLE
Get associated ID to (KEGG/GO/...)-term

### ISSUE THREAD

**Issue by christianholland** [stephenturner/msigdf#4]
Hi there, 

I cannot open an issue at the updated repo from @ToledoEM. Hence I open it here. 

Is it possible to retrieve next to the geneset term also the geneset ID?

E.g. For the term `GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION` the ID would be `GO:0050434`.

Thanks in advance,
Christian

**Comment by ToledoEM** [comment]
Sorry, by mistake the issues were disabled.
Please close this issue and open it in [here](https://github.com/ToledoEM/msigdf/issues).  
Since the information of GO ID is not on msigdb genesets it is not in the package. I am going to explore to add this, but since it is only applicable to the c5 gene set, I would not added to the package.
